name: Canary Build
on:
  pull_request:
    branches: [ main ]

jobs:
  build_rpm:
    name: Build RPM
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up RPM build environment on Ubuntu
        run: |
          # Install RPM build tools on Ubuntu
          sudo apt-get update
          sudo apt-get install -y rpm build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-build python3-installer
          sudo pip3 install build

          # Create RPM build directories
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          echo "%_topdir $HOME/rpmbuild" > ~/.rpmmacros

      - name: Prepare source directory
        run: |
          # Create the source directory in the rpmbuild structure
          mkdir -p ~/rpmbuild/SOURCES/gscreenshot
          
          # Copy all files from the repository to the source directory
          cp -r $(pwd)/* ~/rpmbuild/SOURCES/gscreenshot/
          
          # Display the structure for verification
          echo "Files copied to source directory:"
          find ~/rpmbuild/SOURCES/gscreenshot -type f -name "*.py" | head -10

      - name: Build RPM package
        run: |
          # Build both binary and source RPMs
          rpmbuild -ba ~/rpmbuild/SPECS/gscreenshot-dev.spec
          
          # Output the build result status
          echo "RPM build completed with status: $?"